### Ping Pragma Daemon
GET /ping
Host: localhost:8081

### Migrate project
POST /project/migrate/dev/p1 HTTP/1.1
Host: localhost:8081
Content-Type: application/json

{
    "code": "config { projectName=\"p1\" }\n@1 model User { @1 username: String @primary, @2 password: String, @3 friend: User? }",
    "resolutionPath": "/home/anas/playspace/pragma/todo"
}

### Get Playground
GET /project/p1/dev/graphql HTTP/1.1
Host: localhost:8081

### Execute Playground
POST /project/p1/dev/graphql HTTP/1.1
Host: localhost:8081
Content-Type: application/json

{
    "operationName":null,
    "variables":{},
    "query": "{\n  User {\n    list {\n      username\n    }\n  }\n}\n"
}