### Create project
POST /project/create HTTP/1.1
Host: localhost:3030
Content-Type: application/json

{
    "name": "p1",
    "secret": "123456",
    "pgUri": "jdbc:postgres://localhost:5432/p1",
    "pgUser": "p1",
    "pgPassword": "p1"
}

### Ping Pragma Daemon
GET /ping
Host: localhost:3030