### Ping Pragma Daemon
GET /ping
Host: localhost:3030

### Create project
POST /project/create HTTP/1.1
Host: localhost:3030
Content-Type: application/json

{
    "name": "p1",
    "secret": "123456",
    "pgUri": "jdbc:postgres://localhost:5432/p1",
    "pgUser": "p1",
    "pgPassword": "p1"
}

### Migrate project
POST /project/migrate/dev/p1 HTTP/1.1
Host: localhost:3030
Content-Type: application/json

{
    "code": "config { projectName=\"p1\" }\n@1 model User { @1 username: String @primary, @2 password: String, @3 friend: User? }",
    "functions": []
}